# Generated by Django 6.0.5 on 2026-09-30 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('kirim', 'Kirim'), ('chiqim', 'Chiqim')], max_length=10)),
                ('category', models.CharField(choices=[('ozuqa', 'Ozuqa'), ('dori', 'Dori-darmon'), ('sotuv', 'Sotuv'), ('ish_haqi', 'Ish haqi'), ('kommunal', 'Kommunal xarajat'), ('boshqa', 'Boshqa')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='animals.animalgroup')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-date'],
            },
        ),
    ]
