# Generated by Django 6.1.2 on 2026-10-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='animal_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
