# Generated by Django 6.0.5 on 2026-09-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('kasallik', 'Kasallik'), ('davolash', 'Davolash'), ('vaksinatsiya', 'Vaksinatsiya'), ('tugilish', "Tug'ilish"), ('olim', "O'lim"), ('vazn_olchash', "Vazn o'lchash")], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('boshlangan', 'Boshlangan'), ('davom_etmoqda', 'Davom etmoqda'), ('yakunlangan', 'Yakunlangan')], default='boshlangan', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AnimalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('faol', 'Faol'), ('sotilgan', 'Sotilgan'), ('olgan', "O'lgan"), ('yoqolgan', "Yo'qolgan")], default='faol', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hayvon guruhi',
                'verbose_name_plural': 'Hayvon guruhlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Hayvon turi',
                'verbose_name_plural': 'Hayvon turlari',
            },
        ),
    ]
