# Generated by Django 6.0.5 on 2026-09-30 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animalevent',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animalgroup',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_groups', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='animalevent',
            name='animal_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='animals.animalgroup'),
        ),
        migrations.AddField(
            model_name='animalgroup',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='animals.animaltype'),
        ),
    ]
